# Generated by Django 5.1.3 on 2025-02-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
