# Generated by Django 5.1.3 on 2025-03-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
