# Generated by Django 5.1.3 on 2025-02-17 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_customuser_is_client_customuser_is_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.roles'),
        ),
    ]
