# Generated by Django 5.1.3 on 2025-03-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_report_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
