# Generated by Django 5.1.3 on 2025-02-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
