# Generated by Django 5.1.3 on 2025-01-15 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirement',
            name='max_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requirement',
            name='min_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_points', to='project.requirement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'requirement')},
            },
        ),
    ]
