# Generated by Django 5.1.3 on 2025-03-09 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_last_report_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='points',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='points',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
