# Generated by Django 5.1.3 on 2025-01-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_users_alter_project_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
