# Generated by Django 5.1.3 on 2025-02-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_requirement_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='is_reviewed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
