# Generated by Django 5.1.3 on 2025-03-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_points_created_at_points_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='points',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
