# Generated by Django 5.1.3 on 2025-02-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_requirement_is_reviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='confirmed',
            new_name='canReVote',
        ),
        migrations.AddField(
            model_name='requirement',
            name='canReview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirement',
            name='canVote',
            field=models.BooleanField(default=True),
        ),
    ]
