# Generated by Django 5.1.3 on 2025-01-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_is_active_project_is_finish_voting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='max_points',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='min_points',
        ),
        migrations.AddField(
            model_name='project',
            name='max_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='min_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
