# Generated by Django 5.1.3 on 2025-02-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_confirmed_requirement_canrevote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='canReVote',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='canReview',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='canVote',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='is_reviewed',
        ),
        migrations.AddField(
            model_name='project',
            name='can_review',
            field=models.BooleanField(default=False),
        ),
    ]
