# Generated by Django 5.1.3 on 2025-01-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_requirement_max_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='max_points',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
