# Generated by Django 5.1.3 on 2025-02-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_requirement_canrevote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
