# Generated by Django 5.1.3 on 2025-02-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_requirement_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='p_index',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
