# Generated by Django 5.1.3 on 2025-02-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_requirement_p_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
    ]
